name: Greeting Action
on:
 workflow_dispatch:
   inputs:
     hello:
       type: boolean
       default: true
     bye:
       type: boolean
       default: false
jobs:
 say-hello:
   if: ${{ inputs.hello }}
   runs-on: ubuntu-latest
   steps:
     - run: echo "Hello"
 say-bye:
   if: ${{ inputs.bye }}
   runs-on: ubuntu-latest
   steps:
     - run: echo "Good bye"
